version: '3'

services:
  windscribe-Keeper-Willie:
    image: "concisions/windscribe-socks-server:latest"
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1080:1080
    tmpfs:
      - /etc/windscribe:exec
    environment:
      WINDSCRIBE_DNS: "${WINDSCRIBE_DNS:-1.1.1.1}"
      WINDSCRIBE_USERNAME: "${WINDSCRIBE_USERNAME:?A Windscribe account username must be specified}"
      WINDSCRIBE_PASSWORD: "${WINDSCRIBE_PASSWORD:?A Windscribe account password must be specified}"
      WINDSCRIBE_LOCATION: "Keeper Willie"
      SOCKS_USERNAME_1: "${SOCKS_USERNAME:-}"
      SOCKS_PASSWORD_1: "${SOCKS_PASSWORD:-}"
  windscribe-Biscuits:
    image: "concisions/windscribe-socks-server:latest"
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1081:1080
    tmpfs:
      - /etc/windscribe:exec
    environment:
      WINDSCRIBE_DNS: "${WINDSCRIBE_DNS:-1.1.1.1}"
      WINDSCRIBE_USERNAME: "${WINDSCRIBE_USERNAME:?A Windscribe account username must be specified}"
      WINDSCRIBE_PASSWORD: "${WINDSCRIBE_PASSWORD:?A Windscribe account password must be specified}"
      WINDSCRIBE_LOCATION: Biscuits
      SOCKS_USERNAME_1: "${SOCKS_USERNAME:-}"
      SOCKS_PASSWORD_1: "${SOCKS_PASSWORD:-}"
  windscribe-Crumpets:
    image: "concisions/windscribe-socks-server:latest"
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1082:1080
    tmpfs:
      - /etc/windscribe:exec
    environment:
      WINDSCRIBE_DNS: "${WINDSCRIBE_DNS:-1.1.1.1}"
      WINDSCRIBE_USERNAME: "${WINDSCRIBE_USERNAME:?A Windscribe account username must be specified}"
      WINDSCRIBE_PASSWORD: "${WINDSCRIBE_PASSWORD:?A Windscribe account password must be specified}"
      WINDSCRIBE_LOCATION: Crumpets
      SOCKS_USERNAME_1: "${SOCKS_USERNAME:-}"
      SOCKS_PASSWORD_1: "${SOCKS_PASSWORD:-}"
  windscribe-Custard:
    image: "concisions/windscribe-socks-server:latest"
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1083:1080
    tmpfs:
      - /etc/windscribe:exec
    environment:
      WINDSCRIBE_DNS: "${WINDSCRIBE_DNS:-1.1.1.1}"
      WINDSCRIBE_USERNAME: "${WINDSCRIBE_USERNAME:?A Windscribe account username must be specified}"
      WINDSCRIBE_PASSWORD: "${WINDSCRIBE_PASSWORD:?A Windscribe account password must be specified}"
      WINDSCRIBE_LOCATION: Custard
      SOCKS_USERNAME_1: "${SOCKS_USERNAME:-}"
      SOCKS_PASSWORD_1: "${SOCKS_PASSWORD:-}"